
[default]
mongo_uri = "mongodb://localhost:27017/blog"
extensions = [
    "blog.database:configure",
    "blog.commands:configure",
    "flask_bootstrap:Bootstrap",
    "blog.views:configure",
    "blog.plugins:configure",
    "blog.auth:configure",
    "blog.admin:configure"
]
secret_key = "ef98da23d4dbc2ec406de05733963fd2c90d57e73d81fa6720e1c540cded27a0"
FLASK_ADMIN_SWATCH = "united"